title:  Booj
tagline:  a set of thoughts on security

# Authors documented under _data

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'https-lenpaul-github-io-lagrange'

google-ID: 'UA-80213386-1'

menu:
- {name: 'About', path: 'menu', url: 'about.html'}
- {name: 'Writing', path: 'menu', url: 'writing.html'}
- {name: 'Contact', path: 'menu', url: 'contact.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github', link: 'https://www.github.com/reboare'}
- {icon: 'twitter', link: 'https://twitter.com/reboare'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/josiah-beverton-1b1b22b1/'}
- {icon: 'envelope', link: 'mailto:josiah.beverton@gmail.com'}
- {icon: 'rss-square', link: 'feed.xml'}
